### ISSUE TITLE
Comment BottomSheetModal not working

### ISSUE THREAD

**Issue by knkrth** [Savinvadim1312/YoutubeClone#3]
I got the following error message on browser console on click comment to expand & I got blank full screen,

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at useDerivedValue (Hooks.js:432:1)
    at BottomSheet (BottomSheet.js:97:1)
    at renderWithHooks (react-dom.development.js:14803:1)
    at updateForwardRef (react-dom.development.js:16816:1)
    at beginWork (react-dom.development.js:18645:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22157:1)
    at workLoopSync (react-dom.development.js:22130:1)
    at performSyncWorkOnRoot (react-dom.development.js:21756:1)
    at react-dom.development.js:11089:1
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084:1)
    at flushSyncCallbackQueue (react-dom.development.js:11072:1)
    at flushPassiveEffectsImpl (react-dom.development.js:22883:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushPassiveEffects (react-dom.development.js:22820:1)
    at react-dom.development.js:22699:1
    at workLoop (scheduler.development.js:597:1)
    at flushWork (scheduler.development.js:552:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:164:1)
```

```
The above error occurred in the <ForwardRef(BottomSheet)> component:
    in ForwardRef(BottomSheet)
    in ForwardRef(BottomSheet) (created by ForwardRef(BottomSheetModal))
    in PortalHostComponent (created by PortalProviderComponent)
    in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
    in BottomSheetModalProviderWrapper (at VideoScreen.tsx:128)
    in div (created by View)
    in View (created by SafeAreaView)
    in SafeAreaView (at VideoScreen.tsx:127)
    in VideoScreenWithRecommendation (created by SceneView)
    in StaticContainer
    in StaticContainer (created by SceneView)
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in div (created by View)
    in View (created by CardContainer)
    in div (created by View)
    in View (created by CardContainer)
    in div (created by View)
    in View (created by ForwardRef(CardSheet))
    in ForwardRef(CardSheet) (created by Card)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by ForwardRef(AnimatedComponentWrapper))
    in ForwardRef(AnimatedComponentWrapper) (created by Card)
    in Dummy (created by Card)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (created by ForwardRef(AnimatedComponentWrapper))
    in ForwardRef(AnimatedComponentWrapper) (created by Card)
    in div (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in div (created by View)
    in View (created by WebScreen)
    in WebScreen (created by AnimatedComponent)
    in AnimatedComponent (created by ForwardRef(AnimatedComponentWrapper))
    in ForwardRef(AnimatedComponentWrapper) (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in div (created by View)
    in View (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in CardStack (created by Context.Consumer)
    in KeyboardManager (created by Context.Consumer)
    in SafeAreaProviderCompat (created by StackView)
    in div (created by View)
    in View (created by StackView)
    in StackView (created by StackNavigator)
    in StackNavigator (at navigation/index.tsx:33)
    in RootNavigator (at navigation/index.tsx:22)
    in EnsureSingleNavigator (created by ForwardRef(BaseNavigationContainer))
    in ForwardRef(BaseNavigationContainer) (created by ForwardRef(NavigationContainer))
    in ThemeProvider (created by ForwardRef(NavigationContainer))
    in ForwardRef(NavigationContainer) (at navigation/index.tsx:19)
    in Navigation (at App.tsx:20)
    in div (created by View)
    in View (created by NativeSafeAreaView)
    in NativeSafeAreaView (created by SafeAreaProvider)
    in SafeAreaProvider (at App.tsx:19)
    in App (created by ExpoRootComponent)
    in ExpoRootComponent
    in div (created by View)
    in View (created by AppContainer)
    in div (created by View)
    in View (created by AppContainer)
    in AppContainer

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```
```
Hooks.js:432 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at useDerivedValue (Hooks.js:432:1)
    at BottomSheet (BottomSheet.js:97:1)
    at renderWithHooks (react-dom.development.js:14803:1)
    at updateForwardRef (react-dom.development.js:16816:1)
    at beginWork (react-dom.development.js:18645:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22157:1)
    at workLoopSync (react-dom.development.js:22130:1)
    at performSyncWorkOnRoot (react-dom.development.js:21756:1)
    at react-dom.development.js:11089:1
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084:1)
    at flushSyncCallbackQueue (react-dom.development.js:11072:1)
    at flushPassiveEffectsImpl (react-dom.development.js:22883:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushPassiveEffects (react-dom.development.js:22820:1)
    at react-dom.development.js:22699:1
    at workLoop (scheduler.development.js:597:1)
    at flushWork (scheduler.development.js:552:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:164:1)
useDerivedValue @ Hooks.js:432
BottomSheet @ BottomSheet.js:97
renderWithHooks @ react-dom.development.js:14803
updateForwardRef @ react-dom.development.js:16816
beginWork @ react-dom.development.js:18645
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
```

**Comment by knkrth** [comment]
Found the solution from https://github.com/gorhom/react-native-bottom-sheet/issues/11#issuecomment-916025454
